server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/martiny21/Lab2Tingeso
          search-paths: Backend/config-data
  application:
    name: config-service
