server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
            '[/**]':
              allowredOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://user-service:8090
          predicates:
            - Path=/user/**
        - id: simulate-service
          uri: lb://simulate-service:8081
          predicates:
            - Path=/simulations/**