server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: N0fum4r4S.
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka